export const topicSubtopics = {
  business: [
    "Startups",
    "Corporate News",
    "Mergers & Acquisitions",
    "Real Estate Market",
    "E-commerce",
    "Small Businesses",
    "Investment Strategies",
    "Taxation Policies",
    "Supply Chain & Logistics",
    "Financial Scandals",
  ],
  sports: [
    "Cricket",
    "Football",
    "Tennis",
    "Badminton",
    "Olympics",
    "Basketball",
    "Athletics",
    "Hockey",
    "Golf",
    "Wrestling",
  ],
  technology: [
    "AI",
    "Cybersecurity",
    "Gadgets",
    "Space Exploration",
    "Internet & Connectivity",
    "Robotics",
    "Blockchain & Cryptocurrency",
    "Quantum Computing",
    "Software & Programming",
    "5G & Telecommunications",
  ],
  politics: [
    "Government",
    "Elections",
    "Foreign Policy",
    "Legislation",
    "Political Parties",
    "Political Debates",
    "Protests & Movements",
    "Public Policy",
    "Corruption",
    "Political Scandals",
  ],
  entertainment: [
    "Movies & Cinema",
    "TV Shows & Series",
    "Music & Concerts",
    "Celebrity News & Gossip",
    "Awards & Red Carpet Events",
    "Streaming Platforms",
    "Theater & Performing Arts",
    "Video Games & eSports",
    "Bollywood & Hollywood",
    "Comics & Animation",
  ],
  economy: [
    "Stock Market",
    "Business",
    "Inflation",
    "Trade",
    "Economic Policies",
    "GDP & Growth Rate",
    "Unemployment",
    "Banking & Finance",
    "Real Estate",
    "International Trade",
  ],
  healthcare: [
    "Medicine",
    "Pandemic",
    "Mental Health",
    "Nutrition",
    "Fitness & Exercise",
    "Healthcare Policies",
    "Diseases & Vaccines",
    "Alternative Medicine",
    "Public Health",
    "Medical Research",
  ],
  crime: [
    "Law Enforcement",
    "Court Cases",
    "Scams & Frauds",
    "Violence",
    "Cybercrime",
    "White-Collar Crime",
    "Drug Trafficking",
    "Kidnapping",
    "Human Trafficking",
    "Organized Crime",
  ],
  education: [
    "Schools",
    "Universities",
    "Scholarships",
    "Research",
    "Online Learning",
    "Examinations & Results",
    "Student Loans",
    "Educational Policies",
    "Teaching Methods",
    "EdTech",
  ],
  environment: [
    "Climate Change",
    "Renewable Energy",
    "Deforestation",
    "Wildlife Conservation",
    "Pollution & Air Quality",
    "Ocean & Marine Life",
    "Natural Disasters",
    "Sustainable Development",
    "Carbon Emissions",
    "Water Crisis",
  ],
  science: [
    "Space Exploration",
    "Astronomy",
    "Physics",
    "Biology & Genetics",
    "Chemistry",
    "Scientific Discoveries",
    "AI in Science",
    "Renewable Energy Technologies",
    "Geology & Earth Science",
    "Research & Innovations",
  ],
} as const

export type TopicKey = keyof typeof topicSubtopics

